language: python
python:
  - "3.4"
# command to install dependencies
install:
  - pip install pep8 --use-mirrors
before_script:
  - "pep8 --exclude=migrations --ignore=E501,E225 src"
# command to run tests
script: python src/HelloWorldTest.py