language: python
python:
  - "3.4"
# command to install dependencies
install:
  - pip install pep8 --use-mirrors
before_script:
  - "pep8 --exclude=migrations --show-source --show-pep8 --ignore=E501,E225,E302,E265,W292,W293 src"
# command to run tests
script: python src/HelloWorldTest.py